version: '3'

services:
  servicio1:
    build:
      context: .
    ports:
      - "8581:80"
    volumes:
      - D:\OneDrive - Indra\Escritorio\DockerPHP\Jessika Florez 2672501\datadrive:/datadrive
    networks:
      - mynetwork
    # Otros ajustes necesarios para la accesibilidad

  servicio2:
    image: mysql
    ports:
      - "3336:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysecretpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: myuserpassword
    networks:
      - mynetwork

networks:
  mynetwork:
